# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qgis2DDC
                                 A QGIS plugin
 Connect software "DROIT DE CITE" to QGIS 3.xx
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-23
        copyright            : (C) 2018 by Fred-V13
        email                : fredV13@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qgis2DDC class from file Qgis2DDC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WFS2Spatialite4cache import PyWfs2Spatia4cacheINIT
    return PyWfs2Spatia4cacheINIT(iface)
